version: '3.3'
services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1089
      - MYSQL_DATABASE=client
  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8089:80
    environment:
      - PMA_ARBITRARY=1
